resourcestring                                     {deutsch}

progname='Bistory - Hilfe bei Terminal-Befehlen';
version='V0.1';

defaultcat='Nicht zugeordnet';
capCategory='Kategorie';
hntCategory='Einordnung des Kommandos.';
capCommand='Kommando';
capCommands='Terminal Kommandos';
hntCommand='Das Kommando, welches ausgeführt werden soll.';
capInfo='Beschreibung / Hinweis';
hntInfo='Kurzbeschreibung des Terminalkommandos.';

capClose='&Beenden';
hntClose='Programm beenden.';
capLoadHist='&History';
hntLoadHist='bash Historie einlesen.';
capNew='&Neu';
hntNew='Ein neues Kommando anlegen.';
capAdd='&Einfügen';
hntAdd='Das neue Kommando zur Liste hinzufügen.';
capExecute='&Ausführen';
hntExecute='Das Kommando ausführen.';
capAbout='Über Bistory';
capManual='Anleitung';
hntManual='Informationen zum Programm anzeigen.';
capGit='Bistory Homepage';
hntGit='Programminformationen und Quelltexte in GitHub.';
capHilfe='Hilfe';
capDatei='Datei';
capTools='Tools';
capCopy='Kopieren';
hntCopy='Kommando in die Zwischenablage kopieren';
capEdit='Edit';
hntEdit='Editierte Daten eintragen';
capDelete='Löschen';
hntDelete='Ausgewählten Eintrag löschen.';
defaultcommand='System#sudo apt update && sudo apt upgrade -y#Letzte Updates einbringen';

errNoData='Keine Daten in ';
errNoCmd='Kein Kommando eingegeben';
errCmdFailed='Command failed';

sAdded=' eingefügt';
sExecuted=' ausgeführt';
sEdited=' geändert';
sDeleted=' gelöscht';

