resourcestring                                     {deutsch}

progname='Bistory - Hilfe bei Terminal-Befehlen';
version='V0.1';

defaultcat='Nicht zugeordnet';
capCategory='Kategorie';
hntCategory='Einordnung des Kommandos.';
capCommand='Kommando';
capCommands='Terminal Kommandos';
hntCommand='Das Kommando, welches ausgeführt werden soll.';
capInfo='Beschreibung / Hinweis';
hntInfo='Kurzbeschreibung des Terminalkommandos.';
capTerminal='Terminal';
hntTerminal='Soll beim Ausführen das Terminalfesnter angezeigt werden? Eigentlich fast immer.';

