resourcestring                                     {english}

progname='Bistory - Access to bash history';
version='V0.1';

defaultcat='Undefined';
capCategory='Category';
hntCatrgory='Category of the command.;
capCommand='Command';
hntCommand='Command to be executed.';
capCommands='Terminal Kommandos';
capInfo='Description / Hint';
hntInfo='Short description of the command';
capTerminal='Terminal';
hntTerminal='Show terminal window during execution? Usually true.';


