resourcestring                                     {english}

progname='Bistory - Access to bash history';

defaultcat='Undefined';
capCategory='Category';
hntCatrgory='Category of the command.;
capCommand='Command';
hntCommand='Command to be executed.';
capCommands='Terminal commands';
capInfo='Description / Hint';
hntInfo='Short description of the command';

capClose='&Quit';
hntClose='Close application.';
capLoadHist='&History';
hntLoadHist='Read bash history.';
capNew='&New';
hntNew='Create new command.';
capAdd='&Add';
hntAdd='Add new command to the list.';
capExecute='&Execute';
hntExecute='Execute this command.';
capAbout='About Bistory';
capManual='Manual';
hntManual='Help text about application.';
capGit='Bistory homepage';
hntGit='Information about Bistory and souces in GitHub.';
capHilfe='Help';
capDatei='File';
capTools='Tools';
capCopy='Copy';
hntCopy='Copy command to clipboard';
capEdit='Edit';
hntEdit='Save edited entry.';
capDelete='Delete';
hntDelete='Delete selected command.';
capSaveTitle='Save result to ...';
capResult='Result';
defaultcommand='Info#ip a#Show my IP address';

errNoData='No data in ';
errNoCmd='No command entered';
errCmdFailed='Command failed';

sAdded=' added';
sExecuted=' executed';
sEdited=' edited';
sDeleted=' deleted';

